repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.3.0
      hooks:
        -   id: check-yaml
        -   id: end-of-file-fixer
        -   id: trailing-whitespace
        - id: check-added-large-files

  -   repo: https://github.com/segmentio/golines
      rev: v0.12.2
      hooks:
        -   id: golines

  -   repo: https://github.com/golangci/golangci-lint
      rev: v1.63.4
      hooks:
        -   id: golangci-lint
